"""Fleet ground-truth test: no parser publishes a system_info field whose
own firmware hides it from the user.

Sibling of ``test_channel_field_completeness`` and the same blindness it
closes, one layer over: ``modem.expected.json`` is generated by running the
parser against ``modem.har``, so when a mapping labels a byte wrongly both
files agree and ``test_modem_har_replay`` passes. Replay proves we read the
byte, never that the label is true.

``internet_access`` is the documented case. Netgear's ``InitCableDiagTagValue``
carries the value at offset 0, and the consumer in the same script,
``InitCableDiagUpdateView``, gates the whole row on offset 6::

    if(tagValues[6] == "0") { $("#internetTR").hide(); $("#cmTR").show(); }

Every Netgear capture in the catalog has offset 6 == "0" and offset 0 == "0",
so the firmware hides the Internet row and paints the Cable Modem row green
from offset 7. Reading offset 0 in isolation gives "Down" on a modem whose
own diagnostic page reports "Your setup looks fine."

The guard is fleet-wide rather than per-entry because parsers are built from
sibling templates, so one wrong mapping propagates to every entry that copies
it.

Add to ``_GATED_SYSTEM_INFO_FIELDS`` only with the same evidence: the
firmware's own consumer function, quoted, showing the field is conditionally
hidden and that the condition holds in every committed capture.
"""

from __future__ import annotations

import json
from pathlib import Path

# system_info fields no catalog entry may map, with the reason each is barred.
# Keep tight — every entry here is a fleet-wide assertion.
_GATED_SYSTEM_INFO_FIELDS: dict[str, str] = {
    "internet_access": (
        "Netgear InitCableDiagUpdateView hides the Internet row when "
        "InitCableDiagTagValue offset 6 is '0', which it is in every "
        "committed capture. Use offset 7 (cable modem indicator) if a "
        "connectivity signal is wanted from this block."
    ),
}


def _golden_paths() -> list[Path]:
    """Every committed golden in the catalog."""
    catalog = Path(__file__).parent.parent / "solentlabs" / "cable_modem_monitor_catalog" / "modems"
    return sorted(catalog.rglob("test_data/*.expected.json"))


def test_no_golden_publishes_a_gated_field() -> None:
    """No golden carries a system_info field its firmware hides."""
    offenders: list[str] = []
    for path in _golden_paths():
        data = json.loads(path.read_text(encoding="utf-8"))
        system_info = data.get("data", data).get("system_info") or {}
        for field in _GATED_SYSTEM_INFO_FIELDS:
            if field in system_info:
                entry = f"{path.parent.parent.parent.name}/{path.parent.parent.name}"
                offenders.append(f"{entry} ({path.name}): {field}={system_info[field]!r}")

    assert not offenders, (
        "Goldens publish firmware-hidden system_info fields:\n  "
        + "\n  ".join(offenders)
        + "\n\nReasons:\n  "
        + "\n  ".join(f"{k}: {v}" for k, v in _GATED_SYSTEM_INFO_FIELDS.items())
    )


def test_no_parser_maps_a_gated_field() -> None:
    """No parser.yaml maps a gated field, so template reuse cannot spread it."""
    catalog = Path(__file__).parent.parent / "solentlabs" / "cable_modem_monitor_catalog" / "modems"
    offenders: list[str] = []
    for path in sorted(catalog.rglob("parser.yaml")):
        text = path.read_text(encoding="utf-8")
        for field in _GATED_SYSTEM_INFO_FIELDS:
            # Match the mapping declaration, not a comment mentioning the name.
            if f"field: {field}" in text:
                entry = f"{path.parent.parent.name}/{path.parent.name}"
                offenders.append(f"{entry}: maps {field}")

    assert not offenders, "parser.yaml files map firmware-hidden fields:\n  " + "\n  ".join(offenders)
